const fs = require('fs-extra');

const createTheme = (dirDst, theme) => {
  console.log(`Write ${dirDst}/src/theme/index.js`);
  const fileContent = `\
// NOTICE: This file is auto-generated by wl-engine.
export { default } from './themes/${theme}';
`;
  fs.writeFileSync(`${dirDst}/src/theme/index.js`, fileContent);
};

module.exports = createTheme;
